# Generated by Django 5.1 on 2025-02-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('check_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_attempts', to='checks.check')),
            ],
        ),
    ]
