# Generated by Django 5.1.6 on 2025-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_failedcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='grace_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='check',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='check',
            name='grace_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
